name: miracle_experience_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+6

environment:
  sdk: ^3.9.2

dependencies:
  # android_intent_plus: ^6.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.1.0
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_kronos_plus:
    git:
      url: https://github.com/Stif-UK/flutter-kronos-plus.git
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.2
  meta: ^1.16.0
  no_screenshot: ^0.3.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  restart_app: ^1.3.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  shorebird_code_push: ^2.0.5
  signature: ^6.3.0
  timezone: ^0.10.1
  upgrader: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - shorebird.yaml

  fonts:
    - family: Halvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          weight: 400
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        
